logging:
  level:
    ch.bbw.fabbwled: debug
    org.springframework.web: DEBUG
    root: info
  pattern:
    dateformat: HH:mm:ss
server:
  error:
    include-stacktrace: on_param
  servlet:
    session:
      cookie:
        http-only: false
        secure: true
spring:
  application:
    name: faBBWled lands
  jackson:
    serialization:
      indent-output: true
  output:
    ansi:
      enabled: ALWAYS
springdoc:
  api-docs:
    path: "/api-docs"
